-- data base design

-- A SELECT statement is a read-only operation

-- CREATE, INSERT, UPDATE, AND DELETE

CREATE TABLE COMPANY(
	COMPANY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(60),
	PRIMARY_CONTACT_ID INTERGER NOT NULL
);

CREATE TABLE ROOM(
	ROOM_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
	FLOOR_NUMBER   INTEGER NOT NULL,
	SEAT_CAPACITY  INTEGER NOT NULL
);

CREATE TABLE PRESENTATION(
	PRESENTATION_ID   INTEGER PRIMARY KEY AUTOINCREMENT,
	BOOKED_COMPANY_ID INTEGER NOT NULL,
	BOOKED_ROOM_ID    INTEGER NOT NULL,
	START_TIME        TIME,
	END_TIME          TIME
);

CREATE TABLE ATTENDEE(
	ATTENDEE_ID      INTEGER         PRIMARY KEY AUTOINCREMENT,
	FIRST_NAME       VARCHAR(30)     NOT NULL,
	LAST_NAME        VARCHAR(30)     NOT NULL,
	PHONE            INTEGER,
	EMAIL            VARCHAR(30),
	VIP              BOOLEAN         DEFAULT (0)
);

CREATE TABLE PRESENTATION_ATTENDANCE(
	TICKET_ID           INTEGER PRIMARY KEY AUTOINCREMENT,
	PRESENTATION_ID     INTEGER,
	ATTENDEE_ID         INTEGER
);

-- SELECT  -- foreign key and join ***

CREATE VIEW [VIEW] AS
    SELECT NAME AS BOOKED_COMPANY,
           BOOKED_ROOM_ID AS ROOM_NUMBER,
           FLOOR_NUMBER AS FLOOR,
           SEAT_CAPACITY AS SEATS,
           START_TIME,
           END_TIME
      FROM PRESENTATION
           INNER JOIN
           COMPANY ON PRESENTATION.BOOKED_COMPANY_ID = COMPANY.COMPANY_ID
           INNER JOIN
           ROOM ON PRESENTATION.BOOKED_ROOM_ID = ROOM.ROOM_ID;
		   
